version: '3.8'

services:
  # Main application
  hackrx-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: hackrx-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # Flask configuration
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      
      # Application configuration
      - PYTHONPATH=/app
      
      # API Keys (set these in your environment or .env file)
      - GROQ_API_KEY=${GROQ_API_KEY:-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}
      - API_BEARER_TOKEN=${API_BEARER_TOKEN:-9f40f077e610d431226b59eec99652153ccad94769da6779cc01725731999634}
    
    volumes:
      # Persist data directories
      - ./processing_results:/app/processing_results
      - ./document_processing/logs:/app/document_processing/logs
      - ./document_processing/metadata:/app/document_processing/metadata
      - ./document_processing/embeddings:/app/document_processing/embeddings
      - ./vectorstore:/app/vectorstore
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  default:
    name: hackrx-network